id: A45DA438E
title: Prayer to the Lineage of the Great Chetsün’s Profound Essence of Vimala
type: translation
pechas:
- I88408A8C
- I4BC41024
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:14:37.416629
  last_modified_at: 2023-01-04 12:14:37.416632
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I88408A8C/9488: FB9F
  I4BC41024/1CB2: FB9F
